---

- name: "Block Kafka Bin"
  when: common_kafkabin | bool
  block:
    - name: "Kafka Bin -> create working directory"
      ansible.builtin.file:
        path: "{{ common_kafkabin_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ common_kafkabin_user }}"
        group: "{{ common_kafkabin_group }}"
      become: true
    - name: "Kafka Bin -> download kafka"
      ansible.builtin.unarchive:
        src: "{{ common_kafkabin_src }}"
        dest: "{{ common_kafkabin_dir }}"
        owner: "{{ common_kafkabin_user }}"
        group: "{{ common_kafkabin_group }}"
        creates: "{{ common_kafkabin_dir }}/kafka_{{ common_kafkabin_scala_ver }}-{{ common_kafkabin_ver }}"
        remote_src: true
    - name: "Kafka Bin -> create symlink"
      ansible.builtin.file:
        src: "{{ common_kafkabin_dir }}/kafka_{{ common_kafkabin_scala_ver }}-{{ common_kafkabin_ver }}"
        dest: "{{ common_kafkabin_dir }}/current"
        state: link
        owner: "{{ common_kafkabin_user }}"
        group: "{{ common_kafkabin_group }}"
    # - name: "Kafka Bin -> update PATH"
    #   ansible.builtin.blockinfile:
    #     path: "{{ common_profile_usr_file }}"
    #     block: |
    #       export PATH="{{ common_kafkabin_dir }}/current/bin:$PATH"
    - name: "Kafka Bin -> create user Configuration"
      ansible.builtin.copy:
        content: |
          "{{ item.config }}"
        dest: "{{ common_kafkabin_dir }}/current/config/{{ item.file }}"
        mode: "0644"
        owner: "{{ common_kafkabin_user }}"
        group: "{{ common_kafkabin_group }}"
      with_items: "{{ common_kafkabin_config }}"
      loop_control:
        label: "{{ item.file }}"
      no_log: true
