---

- name: "Block Kafka Bin"
  when: common_kafkabin | bool
  block:
    - name: "Kafka Bin -> create working directory"
      ansible.builtin.file:
        path: "{{ common_kafkabin_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ common_kafkabin_user }}"
        group: "{{ common_kafkabin_group }}"
      become: true
    - name: "Kafka Bin -> download kafka"
      ansible.builtin.unarchive:
        src: "{{ common_kafkabin_src }}"
        dest: "{{ common_kafkabin_dir }}"
        remote_src: true
        creates: "{{ common_kafkabin_dir }}/kafka_{{ common_kafkabin_scala_ver }}-{{ common_kafkabin_ver }}"
