# This file includes all the tasks that are to be executed by the role.
---

- name: "Include Tasks Linux"
  ansible.builtin.include_tasks: "{{ item }}"
  when: ansible_facts.system == 'Linux'
  loop:
    - ./linux/sudoers.yml
    - ./linux/hostname.yml
    - ./linux/profile.yml
    - ./linux/packages.yml
    - ./linux/confluentcli.yml

- name: "Include Tasks Custom"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - kafkabin.yml
