# This file includes all the tasks that are to be executed by the role.
---

- name: "Include Tasks"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - sudoers.yml
    - hostname.yml
    - profile.yml
    - packages.yml
