---

- name: "Confluent CLI Block"
  when: confluentcli | bool
  block:
    - name: "Confluent CLI -> add apt key"
      ansible.builtin.apt_key:
        url: "{{ common_confluentcli_apt_key }}"
        state: present
      when: ansible_pkg_mgr == 'apt'
      become: true
