---

- name: "Confluent CLI Block"
  when: common_confluentcli | bool
  block:
    - name: "Confluent CLI -> add apt key"
      ansible.builtin.apt_key:
        url: "{{ common_confluentcli_apt_key }}"
        state: present
      when: ansible_pkg_mgr == 'apt'
      become: true
    - name: "Confluent CLI -> add apt repository"
      ansible.builtin.apt_repository:
        repo: "{{ common_confluentcli_apt_repo }}"
        state: present
        filename: "{{ common_confluentcli_apt_repo_file }}"
        update_cache: true
      when: ansible_pkg_mgr == 'apt'
      become: true
