---

# - name: "Block APT Package Manager"
#   when: ansible_pkg_mgr == "apt"
#   block:
#     - name: "APT Package Manager -> add key"
#       ansible.builtin.apt_key:
#         url: "{{ common_packages_mgr_config }}"
#         state: present
#       when: ansible_pkg_mgr == 'apt'
#       become: true


- name: "Install Packages"
  ansible.builtin.package:
    name: "{{ package_item }}"
    state: present
  with_items: "{{ common_packages + common_packages_custom }}"
  loop_control:
    loop_var: package_item
  become: true
  when: common_packages | length > 0 or common_packages_custom | length > 0

- name: "Install Snap Packages"
  community.general.snap:
    name: "{{ snap_item }}"
    state: present
  with_items: "{{ common_packages_snap }}"
  loop_control:
    loop_var: snap_item
  when: common_packages_snap | length > 0
  become: true
