---

- name: "Install Packages"
  ansible.builtin.package:
    name: "{{ package_item }}"
    state: present
  loop: "{{ common_packages + common_packages_custom }}"
  loop_control:
    loop_var: package_item
  become: true
  when: common_packages | length > 0 or common_packages_custom | length > 0
