---

- name: "Customise Dconf Database"
  when: common_ubuntu_dconf | length > 0
  with_items: "{{ common_ubuntu_dconf }}"
  loop_control:
    loop_var: "dconf"
  community.general.dconf:
    key: "{{ dconf.key }}"
    value: "{{ dconf.value }}"
    state: "{{ dconf.state }}"

- name: "Sleep Configuration"
  when: common_ubuntu_sleep_conf | length > 0
  block:
    - name: "Create Sleep Systemd Directory"
      ansible.builtin.file:
        path: "{{ common_ubuntu_sleep_conf_dir }}"
        state: directory
        mode: "0755"
        owner: "root"
        group: "root"
      become: true
    - name: "Create Sleep Config"
      ansible.builtin.template:
        src: sleep.j2
        dest: "{{ common_ubuntu_sleep_conf_dir }}/{{ common_ubuntu_sleep_conf_file }}"
        mode: "0644"
        owner: "root"
        group: "root"
      become: true

- name: "Install Ubuntu Packages from the Internet"
  when: common_ubuntu_packages | length > 0
  with_items: "{{ common_ubuntu_packages }}"
  loop_control:
    loop_var: "package"
  become: true
  ansible.builtin.apt:
    deb: "{{ package }}"

- name: "Uninstall and Purge Ubuntu Packages"
  when: common_ubuntu_packages_remove | length > 0
  with_items: "{{ common_ubuntu_packages_remove }}"
  loop_control:
    loop_var: "package"
  become: true
  ansible.builtin.apt:
    name: "{{ package }}"
    state: absent
    purge: true
